build: put entire script in action

diff --git a/.github/actions/extract-version/action.yaml b/.github/actions/extract-version/action.yaml
--- a/.github/actions/extract-version/action.yaml
+++ b/.github/actions/extract-version/action.yaml
@@ -22,6 +22,17 @@ runs:
       id: extract-version
       shell: bash
       run: |
-        version="${{ inputs.tag }}"
-        echo $version
-        exit 1
+        1="${{ inputs.tag }}"
+
+        validate_input() {
+            if [[ ! "$1" =~ ^@[^@]+/[^@]+@[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+                echo "Error: Input string must be in the format '@<namespace>/<name>@<semver-version>'"
+                exit 1
+            fi
+        }
+
+        validate_input "$1"
+
+        version=$(echo "$1" | sed 's/.*@[^@]*@\([^@]*\)/\1/')
+
+        echo "version=$version" >> "$GITHUB_OUTPUT"
